name: iOS Build

on:
  push:
    branches:
      - master

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install Dependencies
        run: yarn install

      - name: Clean CocoaPods cache
        run: |
          pod cache clean --all
          rm -rf ~/Library/Caches/CocoaPods
          rm -rf ios/Pods
          rm -rf ios/Podfile.lock

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          cd ios
          pod install --repo-update

      - name: Set NODE_BINARY for Hermes
        run: echo "NODE_BINARY=$(which node)" >> $GITHUB_ENV

      - name: Symlink node for Hermes (workaround)
        run: |
          NODE_PATH=$(which node)
          sudo mkdir -p /usr/local/opt/node@20/bin
          sudo ln -sf $NODE_PATH /usr/local/opt/node@20/bin/node

      - name: Build iOS App
        run: |
          cd ios
          xcodebuild -workspace MyCareBridge.xcworkspace -scheme MyCareBridge -sdk iphonesimulator -configuration Release

      - name: Upload Build Artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: ios/build/Release-iphoneos/